print("hello world!")
print("welcome home anand")
print("USA")
print("Canada")
print("Germany")
print(8* "\n" )
print("welcome home anand")
print("welcome home", end= '')
print(" anand", end='!')
